allow for keras model difference only

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -79,10 +79,13 @@ jobs:
             pisces_setup
             nbdev_export
             if [[ `git status --porcelain -uno` ]]; then
-              echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
-              git status -uno
-              git diff
-              exit 1;
+              # allow changes only on pisces/cached_models/mo_resunet.keras
+              if [[ `git status --porcelain -uno` | grep -v "cached_models/mo_resunet.keras"` ]]; then
+                echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
+                git status -uno
+                git diff
+                exit 1;
+              fi
             fi
             if [ ! $SKIP_TEST ]; then
               nbdev_test --flags "$FLAGS"
